language: go
go:
- 1.9
services:
- docker
install:
- go get github.com/kardianos/govendor
script:
- make travisbuild
after_success:
- make release
matrix:
  fast_finish: true
  allow_failures:
  - go: tip
env:
  global:
    secure: uBzanAETOmx2YE00DATZXQOV7HO5dNDk7+mW84GJMRPZnUPsc9EJuWRLkygbHg6d93a/dtUpTTfqjJFDLKkNEnl8AEy3Spv431CBLris2K2g0R/UM9zr7rW1u41UW/OvWiX9jCbd+TTdX8s9cX5MA6l43uc1S/7duFgJwBWjwuWXu/x4HJ2TIimnXtRrdZE6xhli/oGjqptnca+LsaNw9tic/mBCo20MemreSiI7I0REokayiUkIuUCHFPK1jFSOIijcMmUgO3p3sfhHdFj9vumxELO620vkOm2eKR4I1uTbyy3tew7WCEKf1v5fElWREkeq87oklJ9jND+t4hWMgRHpEMYtxvcbDIq0uaDbWIcnk7clDnixGvh1oJsEW6bpZ5JIYyMVvM37p+g5QFcOZ7LD7Vgz8yo3shraZufygh7hoZQSgWbhLA5OrcAJFvfXDbGK8KoiZ4djwAhtGlExcRejsxx1csurJe68y3/7K3IAhN5xGHVr+LZWkK4Fr7u407tB9z29kkeIIf06LRIopKE7547dWmFeU+andzY0Ia+lwPce9FVhEqxi3TBM9V83f5rADRqFjXaC5IDXOLKSalJPAVdsW1a42VDIFO16g1/fnvXV7k+83yR/ebNNyS6TUESUnctqiOKpE3WaQoo/LvSxrYNZi4qzroKNiUbSMYk=
