language: go
go:
- 1.9
services:
- docker
install:
- go get github.com/kardianos/govendor
script:
- make travisbuild
after_success:
- make release
matrix:
  fast_finish: true
  allow_failures:
  - go: tip
env:
  global:
  - secure: sJwM/jLG6nbDWnGrqrvE/KJGLE3zJ3K8jRhc5qJyYiSJHB7IdZZEprs4yTN/RlXKOIvJdeglLJSfVQ1zN58HirwRMzbFNrHUOdMD0Sy8iuolFeNwllgB+ksRD+dA6sVK0Ujn+hkba1whqYpx0xzXQy/2pGtXJtbFXUDRcRmfvkk2QfwPP6ocgthGNZRzxnp4I0JPcK5maKizerl1BMjJqwUuGG7AnQi0oiHyR1OthZ0EMtCMOMpOQqQbUU7qa3SqbVzTqUKIvwKGuH9wVeGrw9ffokmGVQpme8op08doYnetBz9KE7XNXWM3jEcxxqDgOqVHdNRO8xZznZhT82TBSvj3oPe0uA6mznV8G7pzwwBCwimiuHGUA/iDuBx8kbMu8UsGiiAHzohO9B5ExbNqmD+iT2/MG+NqeDOoZh90t86swK8zW2aPpR0VIoKrzOyFJ5QQhtCCQTrz+Ll6BqOYmI9e54zPqrSw9c0y/RZJ9fwinPTgPUUhUD6O2TotLyxuvhe8ILzGH/qqoJ+wveA5QXAZQ9cOI0Fb+MmMGnrlQzN6qMwMXohnr+XZ8N873VuLpLu11y335ao72ZVM0rAodqRhxiPLSWzoI09fVY/EnAaURT9hmiM0NDyxr/coX8W+eoz6ZnuJ7P/LNJVsMzbzkmB01Dvsn4Nx35GwgbkcCxQ=
